spring.application.name=backend

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/lingocard_db
spring.datasource.username=postgres
spring.datasource.password=password123

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
